import com.fasterxml.jackson.databind.*;
import java.time.*;
import java.util.*;
import org.gotson.komga.interfaces.api.rest.dto.*;
import org.gotson.komga.interfaces.api.kobo.dto.*;
var m = org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.json().featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS).featuresToEnable(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES, MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES).build();
void p(String name, Object o) { try { System.out.println("W\t" + name + "\t" + m.writeValueAsString(o)); } catch (Exception e) { System.out.println("W\t" + name + "\tERR " + e.getClass().getSimpleName()); } }
void r(String name, String json, Class<?> c) { try { Object o = m.readValue(json, c); System.out.println("R\t" + name + "\t" + m.writeValueAsString(o)); } catch (Exception e) { System.out.println("R\t" + name + "\tERR " + e.getClass().getSimpleName()); } }
void rb(String name, String json, Class<?> c, String... props) { try { Object o = m.readValue(json, c); var sb = new StringBuilder(); for (String pp : props) { boolean b = (Boolean) c.getMethod("isSet", String.class).invoke(o, pp); sb.append(pp).append("=").append(b).append(","); } System.out.println("B\t" + name + "\t" + m.writeValueAsString(o) + "\t" + sb); } catch (Exception e) { System.out.println("B\t" + name + "\tERR " + e.getClass().getSimpleName()); } }
var U = "Été – 日本語 😀 \"q\" \\ \n\t/";
var ldt = LocalDateTime.of(2024, 3, 5, 7, 8, 9, 123456789);
var ldt0 = LocalDateTime.of(2024, 3, 5, 7, 8);
var ld = LocalDate.of(2024, 3, 5);
var zdt = ZonedDateTime.of(2024, 3, 5, 7, 8, 9, 120000000, ZoneOffset.ofHours(2));
var zdt0 = ZonedDateTime.of(2024, 3, 5, 7, 8, 0, 0, ZoneOffset.UTC);
// ---- rest dto (write)
p("AlternateTitleDto", new AlternateTitleDto("fr", U));
p("ApiKeyDto", new ApiKeyDto("id1", "user1", "key", U, zdt, zdt0));
p("AuthenticationActivityDto.nulls", new AuthenticationActivityDto(null, null, null, null, null, null, false, null, ldt, null));
p("AuthenticationActivityDto.full", new AuthenticationActivityDto("u", "a@b.c", "k", "c", "127.0.0.1", U, true, "err", ldt0, "Password"));
p("AuthorDto", new AuthorDto(U, "writer"));
var media = new MediaDto("READY", "application/zip", 12, "", true, false);
var media2 = new MediaDto("ERROR", "application/x-unknown", 0, U, false, true);
var bmeta = new BookMetadataDto("t", true, U, false, "1.5", true, 1.5f, false, ld, true, List.of(new AuthorDto("n", "r")), false, new LinkedHashSet<>(List.of("b", "a")), true, "978", true, List.of(new WebLinkDto("l", "https://x/y?z=1")), false, ldt, ldt0);
var bmeta2 = new BookMetadataDto("", false, "", false, "", false, 0.1f, false, null, false, List.of(), false, Set.of(), false, "", false, List.of(), false, ldt0, ldt);
var rp = new ReadProgressDto(3, false, ldt, ldt0, ldt, "dev", U);
p("MediaDto", media);
p("MediaDto.unknown", media2);
p("BookMetadataDto", bmeta);
p("BookMetadataDto.empty", bmeta2);
p("ReadProgressDto", rp);
p("BookDto", new BookDto("b1", "s1", U, "l1", "name", "/a/b/c.cbz", 7, ldt, ldt0, ldt, 2048L, com.jakewharton.byteunits.BinaryByteUnit.format(2048L), media, bmeta, rp, false, "hash", true));
p("BookDto.noProgress", new BookDto("b2", "s1", "st", "l1", "name", "c.cbz", 0, ldt0, ldt0, ldt0, 5000000000L, "4,7 GiB", media2, bmeta2, null, true, "", false));
p("BookDto.restrictUrl", BookDtoKt.restrictUrl(new BookDto("b2", "s1", "st", "l1", "name", "/x/y\\z.cbz", 0, ldt0, ldt0, ldt0, 512L, com.jakewharton.byteunits.BinaryByteUnit.format(512L), media2, bmeta2, null, true, "", false), true));
p("BookImportBatchDto", new BookImportBatchDto(List.of(new BookImportDto("/a", "s", null, null), new BookImportDto("/b", "s", "u", "d")), org.gotson.komga.domain.model.CopyMode.HARDLINK));
p("ClientSettingDto", new ClientSettingDto("v", true));
p("ClientSettingDto.null", new ClientSettingDto(U, null));
p("ClientSettingGlobalUpdateDto", new ClientSettingGlobalUpdateDto("v", false));
p("ClientSettingUserUpdateDto", new ClientSettingUserUpdateDto("v"));
p("CollectionCreationDto", new CollectionCreationDto("n", true, List.of("a", "b")));
p("CollectionDto", new CollectionDto("c1", U, false, List.of(), ldt, ldt0, true));
p("CollectionUpdateDto", new CollectionUpdateDto(null, null, null));
p("GithubReleaseDto", new GithubReleaseDto("https://h", "1.0.0", zdt, U, false));
p("GroupCountDto", new GroupCountDto("A", 42));
var props = new LinkedHashMap<String, String>(); props.put("reason", U); props.put("name", "x");
p("HistoricalEventDto", new HistoricalEventDto("e1", "BookFileDeleted", ldt, "b", null, props));
p("HistoricalEventDto.empty", new HistoricalEventDto("e1", "SeriesFolderDeleted", ldt0, null, "s", Map.of()));
var item = new JsonFeedDto.ItemDto("i1", "https://u", "t", "s", "<p>x</p>", OffsetDateTime.of(2023, 12, 15, 0, 0, 0, 0, ZoneOffset.ofHours(1)), new JsonFeedDto.ItemAuthorDto("gotson", null), new LinkedHashSet<>(List.of("upgrade", "komga")), new JsonFeedDto.KomgaExtensionDto(true));
var item2 = new JsonFeedDto.ItemDto("i2", null, null, null, null, null, null, Set.of(), null);
p("JsonFeedDto", new JsonFeedDto("https://jsonfeed.org/version/1", "Announcements", "https://komga.org/blog", U, List.of(item, item2)));
p("JsonFeedDto.ItemDto", item);
p("LibraryCreationDto", new LibraryCreationDto("n", "/r", true, false, true, false, true, false, true, false, true, false, true, ScanIntervalDto.DAILY, false, true, false, true, Set.of("#recycle"), false, true, false, SeriesCoverDto.LAST, true, false, true, false, null));
p("LibraryDto", new LibraryDto("l1", U, "/root", true, false, true, false, true, false, true, false, true, false, true, ScanIntervalDto.EVERY_12H, false, true, false, true, new LinkedHashSet<>(List.of("#recycle", "@eaDir")), false, true, false, SeriesCoverDto.FIRST_UNREAD_OR_LAST, true, false, true, false, "_oneshots", true));
p("PageDto", new PageDto(1, U, "image/jpeg", 800, 1200, 2048L, com.jakewharton.byteunits.BinaryByteUnit.format(2048L)));
p("PageDto.nulls", new PageDto(2, "p.png", "image/png", null, null, null, ""));
p("PageHashCreationDto", new PageHashCreationDto("h", 12L, org.gotson.komga.domain.model.PageHashKnown.Action.DELETE_AUTO));
p("PageHashKnownDto", new PageHashKnownDto("h", null, org.gotson.komga.domain.model.PageHashKnown.Action.IGNORE, 1, 2, ldt, ldt0));
p("PageHashMatchDto", new PageHashMatchDto("b", "/a/b.cbz", 3, "p.jpg", 5000000000L, "image/jpeg"));
p("PageHashUnknownDto", new PageHashUnknownDto("h", 123L, 4));
p("PasswordUpdateDto", new PasswordUpdateDto(U));
var loc = new org.gotson.komga.domain.model.R2Locator("h.xhtml", "application/xhtml+xml", "title", new org.gotson.komga.domain.model.R2Locator.Location(List.of("f"), 0.1f, 3, 1.0f), null, null);
p("R2Positions", new R2Positions(2, List.of(loc, new org.gotson.komga.domain.model.R2Locator("h2", "t", null, null, null, "kobo.1.1"))));
p("R2Positions.empty", new R2Positions(0, List.of()));
p("ReadListCreationDto", new ReadListCreationDto("n", U, false, List.of("a")));
p("ReadListDto", new ReadListDto("r1", "n", U, true, List.of("b1", "b2"), ldt, ldt0, false));
var rlrm = new ReadListRequestMatchDto(new ReadListMatchDto("rl", "ERR_1"), List.of(new ReadListRequestBookMatchesDto(new ReadListRequestBookDto(new LinkedHashSet<>(List.of("S1", "S2")), "1"), List.of(new ReadListRequestBookMatchDto(new ReadListRequestBookMatchSeriesDto("s", U, ld), List.of(new ReadListRequestBookMatchBookDto("b", "1", "t"))), new ReadListRequestBookMatchDto(new ReadListRequestBookMatchSeriesDto("s2", "t2", null), List.of()))), new ReadListRequestBookMatchesDto(new ReadListRequestBookDto(Set.of(), ""), List.of())), "");
p("ReadListRequestMatchDto", rlrm);
p("ReadListUpdateDto", new ReadListUpdateDto("n", null, List.of("a"), true));
p("ReadProgressUpdateDto", new ReadProgressUpdateDto(null, true));
p("ReleaseDto", new ReleaseDto("1.2.3", zdt, "https://u", true, false, U));
var smeta = new SeriesMetadataDto("ONGOING", true, U, false, "ts", true, "sum", false, "LEFT_TO_RIGHT", true, "pub", false, 16, true, "fr", false, new LinkedHashSet<>(List.of("g2", "g1")), true, Set.of(), false, 10, true, Set.of("l"), false, List.of(new WebLinkDto("a", "b")), true, List.of(new AlternateTitleDto("jp", "日本")), false, ldt, ldt0);
var smeta2 = new SeriesMetadataDto("ENDED", false, "", false, "", false, "", false, "", false, "", false, null, false, "", false, Set.of(), false, Set.of(), false, null, false, Set.of(), false, List.of(), false, List.of(), false, ldt0, ldt0);
var bagg = new BookMetadataAggregationDto(List.of(new AuthorDto("a", "b")), new LinkedHashSet<>(List.of("t1", "t2")), ld, U, "3", ldt, ldt0);
var bagg2 = new BookMetadataAggregationDto(List.of(), Set.of(), null, "", "", ldt0, ldt0);
p("SeriesMetadataDto", smeta);
p("BookMetadataAggregationDto", bagg);
p("SeriesDto", new SeriesDto("s1", "l1", U, "/a/b", ldt, ldt0, ldt, 10, 2, 7, 1, smeta, bagg, false, true));
p("SeriesDto.empty", SeriesDtoKt.restrictUrl(new SeriesDto("s2", "l1", "n", "/a/b", ldt0, ldt0, ldt0, 0, 0, 0, 0, smeta2, bagg2, true, false), true));
p("SettingsDto", new SettingsDto(true, false, 365L, ThumbnailSizeDto.LARGE, 4, new SettingMultiSource<Integer>(25600, null, 25600), new SettingMultiSource<String>(null, "/komga", "/komga"), false, 8080, new SettingMultiSource<String>(null, null, null), 5000000000L));
p("SettingsDto.empty", new SettingsDto(null, null, null, null, null, null, null, null, null, null, null));
p("SettingsDto.public", SettingsDtoKt.class.getMethod("public", SettingsDto.class).invoke(null, new SettingsDto(true, false, 365L, ThumbnailSizeDto.LARGE, 4, null, null, false, 8080, null, 1024L)));
p("TachiyomiReadProgressDto", new TachiyomiReadProgressDto(10, 2, 7, 1, 3));
p("TachiyomiReadProgressUpdateDto", new TachiyomiReadProgressUpdateDto(5));
p("TachiyomiReadProgressUpdateV2Dto", new TachiyomiReadProgressUpdateV2Dto(0.1f));
p("TachiyomiReadProgressV2Dto", new TachiyomiReadProgressV2Dto(10, 2, 7, 1, 3.0f, 12.3f));
p("ThumbnailBookDto", new ThumbnailBookDto("t", "b", "GENERATED", true, "image/jpeg", 5000000000L, 300, 400));
p("ThumbnailReadListDto", new ThumbnailReadListDto("t", "r", "USER_UPLOADED", false, "image/png", 12L, 0, 0));
p("ThumbnailSeriesCollectionDto", new ThumbnailSeriesCollectionDto("t", "c", "USER_UPLOADED", false, "image/png", 12L, 1, 2));
p("ThumbnailSeriesDto", new ThumbnailSeriesDto("t", "s", "SIDECAR", true, "image/webp", 12L, 1, 2));
p("UserCreationDto", new UserCreationDto("a@b.c", "p", List.of("ADMIN"), new AgeRestrictionUpdateDto(12, AllowExcludeDto.NONE), null, Set.of("x"), new SharedLibrariesUpdateDto(false, Set.of("l"))));
p("UserDto", new UserDto("u", "a@b.c", new LinkedHashSet<>(List.of("ADMIN", "USER")), false, new LinkedHashSet<>(List.of("l1", "l2")), Set.of(), Set.of("x"), new AgeRestrictionDto(16, org.gotson.komga.domain.model.AllowExclude.EXCLUDE)));
p("UserDto.noAge", new UserDto("u", "a@b.c", Set.of("USER"), true, Set.of(), Set.of(), Set.of(), null));
p("AgeRestrictionUpdateDto", new AgeRestrictionUpdateDto(3, AllowExcludeDto.ALLOW_ONLY));
p("SharedLibrariesUpdateDto", new SharedLibrariesUpdateDto(true, Set.of()));
p("WebLinkDto", new WebLinkDto(U, "https://a/b"));
// ---- rest dto (read)
r("AlternateTitleDto", "{\"label\":\"l\",\"title\":\"t\"}", AlternateTitleDto.class);
r("ApiKeyRequestDto", "{\"comment\":\"c\"}", ApiKeyRequestDto.class);
r("ApiKeyRequestDto.missing", "{}", ApiKeyRequestDto.class);
r("ApiKeyRequestDto.null", "{\"comment\":null}", ApiKeyRequestDto.class);
r("BookImportBatchDto", "{\"books\":[{\"sourceFile\":\"/a\",\"seriesId\":\"s\"},{\"sourceFile\":\"/b\",\"seriesId\":\"s\",\"upgradeBookId\":\"u\",\"destinationName\":null}],\"copyMode\":\"move\"}", BookImportBatchDto.class);
r("BookImportBatchDto.enumCase", "{\"books\":[{\"sourceFile\":\"/a\",\"seriesId\":\"s\"},{\"sourceFile\":\"/b\",\"seriesId\":\"s\",\"upgradeBookId\":\"u\",\"destinationName\":null}],\"copyMode\":\"MOVE\"}", BookImportBatchDto.class);
r("BookImportBatchDto.default", "{\"copyMode\":\"COPY\",\"extra\":1}", BookImportBatchDto.class);
r("BookImportBatchDto.badEnum", "{\"copyMode\":\"XX\"}", BookImportBatchDto.class);
r("ClientSettingGlobalUpdateDto", "{\"value\":\"v\",\"allowUnauthorized\":true}", ClientSettingGlobalUpdateDto.class);
r("ClientSettingGlobalUpdateDto.nullPrimitive", "{\"value\":\"v\",\"allowUnauthorized\":null}", ClientSettingGlobalUpdateDto.class);
r("ClientSettingUserUpdateDto", "{\"VALUE\":\"v\"}", ClientSettingUserUpdateDto.class);
r("CollectionCreationDto", "{\"name\":\"n\",\"ordered\":false,\"seriesIds\":[\"a\",\"a\"]}", CollectionCreationDto.class);
r("CollectionUpdateDto", "{\"name\":\"n\"}", CollectionUpdateDto.class);
r("CollectionUpdateDto.empty", "{}", CollectionUpdateDto.class);
r("GithubReleaseDto", "{\"url\":\"x\",\"html_url\":\"https://github.com/gotson/komga/releases/tag/1.0.0\",\"tag_name\":\"1.0.0\",\"published_at\":\"2024-03-05T07:08:09+02:00\",\"body\":\"b\",\"prerelease\":false,\"assets\":[]}", GithubReleaseDto.class);
r("JsonFeedDto", "{\"version\":\"https://jsonfeed.org/version/1\",\"title\":\"Announcements\",\"home_page_url\":\"https://komga.org/blog\",\"description\":\"d\",\"items\":[{\"id\":\"i\",\"url\":\"u\",\"title\":\"t\",\"summary\":\"s\",\"content_html\":\"<p>x</p>\",\"date_modified\":\"2023-12-15T00:00:00+01:00\",\"author\":{\"name\":\"gotson\",\"url\":\"https://github.com/gotson\"},\"tags\":[\"upgrade\",\"komga\"],\"_komga\":{\"read\":true}},{\"id\":\"i2\"}]}", JsonFeedDto.class);
r("JsonFeedDto.minimal", "{\"version\":\"v\",\"title\":\"t\"}", JsonFeedDto.class);
r("LibraryCreationDto", "{\"name\":\"n\",\"root\":\"/r\"}", LibraryCreationDto.class);
r("LibraryCreationDto.full", "{\"name\":\"n\",\"root\":\"/r\",\"importComicInfoBook\":false,\"scanInterval\":\"weekly\",\"scanDirectoryExclusions\":[\"a\"],\"seriesCover\":\"FIRST_UNREAD_OR_FIRST\",\"oneshotsDirectory\":\"o\",\"hashKoreader\":true}", LibraryCreationDto.class);
r("LibraryCreationDto.full.enumCase", "{\"name\":\"n\",\"root\":\"/r\",\"importComicInfoBook\":false,\"scanInterval\":\"WEEKLY\",\"scanDirectoryExclusions\":[\"a\"],\"seriesCover\":\"FIRST_UNREAD_OR_FIRST\",\"oneshotsDirectory\":\"o\",\"hashKoreader\":true}", LibraryCreationDto.class);
r("LibraryCreationDto.missing", "{\"name\":\"n\"}", LibraryCreationDto.class);
r("PageHashCreationDto", "{\"hash\":\"h\",\"action\":\"DELETE_MANUAL\"}", PageHashCreationDto.class);
r("PageHashCreationDto.size", "{\"hash\":\"h\",\"size\":5000000000,\"action\":\"IGNORE\"}", PageHashCreationDto.class);
r("PasswordUpdateDto", "{\"password\":\"p\"}", PasswordUpdateDto.class);
r("ReadListCreationDto", "{\"name\":\"n\",\"bookIds\":[\"a\"]}", ReadListCreationDto.class);
r("ReadListUpdateDto", "{\"summary\":\"s\",\"ordered\":false}", ReadListUpdateDto.class);
r("ReadProgressUpdateDto", "{\"page\":3}", ReadProgressUpdateDto.class);
r("ReadProgressUpdateDto.completed", "{\"completed\":true}", ReadProgressUpdateDto.class);
r("TachiyomiReadProgressUpdateDto", "{\"lastBookRead\":4}", TachiyomiReadProgressUpdateDto.class);
r("TachiyomiReadProgressUpdateV2Dto", "{\"lastBookNumberSortRead\":0.3}", TachiyomiReadProgressUpdateV2Dto.class);
r("TachiyomiReadProgressUpdateV2Dto.int", "{\"lastBookNumberSortRead\":3}", TachiyomiReadProgressUpdateV2Dto.class);
r("UserCreationDto", "{\"email\":\"a@b.c\",\"password\":\"p\"}", UserCreationDto.class);
r("UserCreationDto.full", "{\"email\":\"a@b.c\",\"password\":\"p\",\"roles\":[\"ADMIN\"],\"ageRestriction\":{\"age\":12,\"restriction\":\"ALLOW_ONLY\"},\"labelsAllow\":[\"a\"],\"labelsExclude\":[],\"sharedLibraries\":{\"all\":false,\"libraryIds\":[\"l\"]}}", UserCreationDto.class);
rb("AlternateTitleUpdateDto", "{\"label\":\"l\"}", AlternateTitleUpdateDto.class);
rb("BookMetadataUpdateDto.empty", "{}", BookMetadataUpdateDto.class, "summary", "releaseDate", "authors", "tags", "isbn", "links");
rb("BookMetadataUpdateDto.nulls", "{\"summary\":null,\"releaseDate\":null,\"authors\":null,\"tags\":null,\"isbn\":null,\"links\":null,\"title\":null}", BookMetadataUpdateDto.class, "summary", "releaseDate", "authors", "tags", "isbn", "links");
rb("BookMetadataUpdateDto.full", "{\"title\":\"t\",\"titleLock\":true,\"summary\":\"s\",\"summaryLock\":false,\"number\":\"1\",\"numberLock\":true,\"numberSort\":0.1,\"numberSortLock\":true,\"releaseDate\":\"2024-03-05\",\"releaseDateLock\":true,\"authors\":[{\"name\":\"n\",\"role\":\"r\"}],\"authorsLock\":true,\"tags\":[\"a\",\"b\"],\"tagsLock\":false,\"isbn\":\"978-1\",\"isbnLock\":true,\"links\":[{\"label\":\"l\",\"url\":\"https://u\"}],\"linksLock\":false}", BookMetadataUpdateDto.class, "summary", "releaseDate", "authors", "tags", "isbn", "links");
rb("LibraryUpdateDto", "{\"name\":\"n\",\"scanInterval\":\"hourly\",\"oneshotsDirectory\":null,\"hashFiles\":false}", LibraryUpdateDto.class, "scanDirectoryExclusions", "oneshotsDirectory");
rb("LibraryUpdateDto.enumCase", "{\"name\":\"n\",\"scanInterval\":\"HOURLY\",\"oneshotsDirectory\":null,\"hashFiles\":false}", LibraryUpdateDto.class, "scanDirectoryExclusions", "oneshotsDirectory");
rb("LibraryUpdateDto.set", "{\"scanDirectoryExclusions\":[\"x\"],\"seriesCover\":\"LAST\"}", LibraryUpdateDto.class, "scanDirectoryExclusions", "oneshotsDirectory");
rb("SeriesMetadataUpdateDto", "{\"status\":\"HIATUS\",\"title\":\"t\",\"summary\":\"s\",\"readingDirection\":null,\"ageRating\":12,\"genres\":[\"g\"],\"totalBookCount\":null,\"links\":[{\"label\":\"l\",\"url\":\"u\"}],\"alternateTitles\":[{\"label\":\"a\",\"title\":\"b\"}],\"language\":\"fr\"}", SeriesMetadataUpdateDto.class, "readingDirection", "ageRating", "genres", "tags", "totalBookCount", "sharingLabels", "links", "alternateTitles");
rb("SeriesMetadataUpdateDto.empty", "{}", SeriesMetadataUpdateDto.class, "readingDirection", "ageRating", "genres", "tags", "totalBookCount", "sharingLabels", "links", "alternateTitles");
rb("SettingsUpdateDto", "{\"deleteEmptyCollections\":true,\"rememberMeDurationDays\":5000000000,\"thumbnailSize\":\"xlarge\",\"serverPort\":null,\"serverContextPath\":\"/k\",\"kepubifyPath\":\"k\"}", SettingsUpdateDto.class, "serverPort", "serverContextPath", "koboPort", "kepubifyPath");
rb("SettingsUpdateDto.enumCase", "{\"deleteEmptyCollections\":true,\"rememberMeDurationDays\":5000000000,\"thumbnailSize\":\"XLARGE\",\"serverPort\":null,\"serverContextPath\":\"/k\",\"kepubifyPath\":\"k\"}", SettingsUpdateDto.class, "serverPort", "serverContextPath", "koboPort", "kepubifyPath");
rb("UserUpdateDto", "{\"ageRestriction\":null,\"roles\":[\"ADMIN\"],\"sharedLibraries\":{\"all\":true,\"libraryIds\":[]}}", UserUpdateDto.class, "ageRestriction", "labelsAllow", "labelsExclude", "roles", "sharedLibraries");
rb("UserUpdateDto.age", "{\"ageRestriction\":{\"age\":10,\"restriction\":\"EXCLUDE\"},\"labelsAllow\":[\"x\"]}", UserUpdateDto.class, "ageRestriction", "labelsAllow", "labelsExclude", "roles", "sharedLibraries");
// ---- kobo dto (write)
p("AmountDto", new AmountDto("USD", 0));
p("AmountDto.null", new AmountDto(null, 5));
p("AuthDto", new AuthDto("a", "r", "Bearer", "t", "u"));
var ent = new BookEntitlementDto("Full", new PeriodDto(zdt0), zdt, "c", "i", false, false, true, zdt0, "Imported", "r", "Active");
var km = new KoboBookMetadataDto(List.of(KoboBookMetadataDtoKt.DUMMY_ID), List.of(new ContributorDto("a")), List.of("a"), "cover", "c", new AmountDto("USD", 0), new AmountDto(null, 0), U, List.of(new DownloadUrlDto("None", FormatDto.KEPUB, 5000000000L, "Generic", "https://u")), "e", List.of(), KoboBookMetadataDtoKt.DUMMY_ID, false, false, false, true, "978", "en", Map.of("a", "b"), zdt, new PublisherDto("", "pub"), "r", new KoboSeriesDto("s", "n", "1.5", 1.5f), "slug", null, "title", "w", true, false, 12L, Map.of("x", 1L));
var km2 = new KoboBookMetadataDto(List.of(), List.of(), List.of(), null, "c", new AmountDto("USD", 0), new AmountDto(null, 0), null, List.of(), "e", List.of(), "", false, false, false, true, null, "en", Map.of(), null, null, "r", null, null, null, "title", "w", false, true, 0L, Map.of());
var bm = new BookmarkDto(zdt, 33.333332f, 0.1f, new LocationDto("kobo.1.1", "KoboSpan", "c.xhtml"));
var rs = new ReadingStateDto(zdt0, bm, "e", zdt, zdt, new StatisticsDto(zdt, 10, null), new StatusInfoDto(zdt, StatusDto.READY_TO_READ, 1, zdt0, null));
var rs2 = new ReadingStateDto(null, new BookmarkDto(zdt0, null, null, null), "e", zdt0, null, new StatisticsDto(zdt0, null, null), new StatusInfoDto(zdt0, StatusDto.FINISHED, null, null, null));
var ctr = new BookEntitlementContainerDto(ent, km, rs);
var tag = new WrappedTagDto(new TagDto("t", zdt, zdt0, U, TagTypeDto.USER_TAG, List.of(new TagItemDto("r", "ProductRevisionTagItem"))));
var tag2 = new WrappedTagDto(new TagDto("t", zdt, zdt0, "n", TagTypeDto.SYSTEM_TAG, null));
p("BookEntitlementContainerDto", ctr);
p("BookEntitlementContainerDto.noState", new BookEntitlementContainerDto(ent, km2, null));
p("BookEntitlementDto", ent);
p("BookmarkDto", bm);
p("BookmarkDto.nulls", new BookmarkDto(zdt0, null, null, null));
p("ContributorDto", new ContributorDto(U));
p("DownloadUrlDto", new DownloadUrlDto("None", FormatDto.EPUB3FL, 1L, "Android", "u"));
p("KoboBookMetadataDto", km);
p("KoboBookMetadataDto.min", km2);
p("KoboSeriesDto", new KoboSeriesDto("s", "n", "1", 0.1f));
p("LocationDto", new LocationDto(null, null, "s"));
p("LocationDto.default", new LocationDto(null, "KoboSpan", "s"));
p("PeriodDto", new PeriodDto(zdt));
p("PublisherDto", new PublisherDto("imp", U));
p("ReadingStateDto", rs);
p("ReadingStateDto.min", rs2);
p("WrappedReadingStateDto", new WrappedReadingStateDto(rs2));
p("ReadingStateStateUpdateDto", new ReadingStateStateUpdateDto(List.of(rs, rs2)));
var rsur = new ReadingStateUpdateResultDto("e", ResultDto.SUCCESS.wrapped(), new WrappedResultDto(ResultDto.FAILURE), new WrappedResultDto(ResultDto.IGNORED));
p("RequestResultDto", new RequestResultDto(ResultDto.SUCCESS, List.of(rsur)));
p("RequestResultDto.empty", new RequestResultDto(ResultDto.IGNORED, List.of()));
p("ReadingStateUpdateResultDto", rsur);
p("WrappedResultDto", new WrappedResultDto(ResultDto.FAILURE));
p("ResourcesDto", new ResourcesDto(m.readTree("{\"a\":1,\"b\":[1.5,\"x\",null,true],\"c\":{\"d\":1.0E10}}")));
p("StatisticsDto", new StatisticsDto(zdt, 1, 2));
p("StatusInfoDto", new StatusInfoDto(zdt, StatusDto.READING, 2, zdt, zdt0));
p("NewEntitlementDto", new NewEntitlementDto(ctr));
p("ChangedEntitlementDto", new ChangedEntitlementDto(new BookEntitlementContainerDto(ent, km2, null)));
p("ChangedProductMetadataDto", new ChangedProductMetadataDto(km2));
p("NewTagDto", new NewTagDto(tag));
p("ChangedTagDto", new ChangedTagDto(tag2));
p("DeletedTagDto", new DeletedTagDto(tag2));
p("ChangedReadingStateDto", new ChangedReadingStateDto(new WrappedReadingStateDto(rs)));
p("SyncResultList", List.<SyncResultDto>of(new NewEntitlementDto(ctr), new NewTagDto(tag2)));
p("TagDto", tag.getTag());
p("WrappedTagDto", tag);
p("TagItemDto", new TagItemDto("r", "x"));
p("TestsDto", new TestsDto("Success", "k", Map.of("t", "v")));
p("TestsDto.empty", new TestsDto("Success", "k", Map.of()));
p("FormatDto", FormatDto.EPUB3);
p("ResultDto", ResultDto.SUCCESS);
p("StatusDto", StatusDto.READY_TO_READ);
p("TagTypeDto", TagTypeDto.SYSTEM_TAG);
// ---- kobo dto (read)
r("ReadingStateStateUpdateDto", "{\"ReadingStates\":[{\"EntitlementId\":\"e\",\"LastModified\":\"2024-03-05T07:08:09.123+02:00\",\"CurrentBookmark\":{\"LastModified\":\"2024-03-05T07:08:09Z\",\"ProgressPercent\":33.3,\"ContentSourceProgressPercent\":0,\"Location\":{\"Value\":\"kobo.1.1\",\"Type\":\"KoboSpan\",\"Source\":\"c.xhtml\"}},\"Statistics\":{\"LastModified\":\"2024-03-05T07:08:09Z\",\"SpentReadingMinutes\":5,\"RemainingTimeMinutes\":1},\"StatusInfo\":{\"LastModified\":\"2024-03-05T07:08:09Z\",\"Status\":\"Reading\",\"TimesStartedReading\":1,\"LastTimeStartedReading\":\"2024-03-05T07:08:09Z\"},\"PriorityTimestamp\":\"2024-03-05T07:08:09Z\"}]}", ReadingStateStateUpdateDto.class);
r("ReadingStateStateUpdateDto.lowercase", "{\"readingStates\":[{\"entitlementId\":\"e\",\"lastModified\":\"2024-03-05T07:08:09Z\",\"currentBookmark\":{\"lastModified\":\"2024-03-05T07:08:09Z\"},\"statistics\":{\"lastModified\":\"2024-03-05T07:08:09Z\"},\"statusInfo\":{\"lastModified\":\"2024-03-05T07:08:09Z\",\"status\":\"finished\"}}]}", ReadingStateStateUpdateDto.class);
r("ReadingStateStateUpdateDto.lowercaseProps", "{\"readingStates\":[{\"entitlementId\":\"e\",\"lastModified\":\"2024-03-05T07:08:09Z\",\"currentBookmark\":{\"lastModified\":\"2024-03-05T07:08:09Z\"},\"statistics\":{\"lastModified\":\"2024-03-05T07:08:09Z\"},\"statusInfo\":{\"lastModified\":\"2024-03-05T07:08:09Z\",\"status\":\"Finished\"}}]}", ReadingStateStateUpdateDto.class);
r("ReadingStateStateUpdateDto.badStatus", "{\"ReadingStates\":[{\"EntitlementId\":\"e\",\"LastModified\":\"2024-03-05T07:08:09Z\",\"CurrentBookmark\":{\"LastModified\":\"2024-03-05T07:08:09Z\"},\"Statistics\":{\"LastModified\":\"2024-03-05T07:08:09Z\"},\"StatusInfo\":{\"LastModified\":\"2024-03-05T07:08:09Z\",\"Status\":\"READING\"}}]}", ReadingStateStateUpdateDto.class);
r("ReadingStateStateUpdateDto.empty", "{}", ReadingStateStateUpdateDto.class);
r("TagDto", "{\"Id\":\"t\",\"Created\":\"2024-03-05T07:08:09Z\",\"LastModified\":\"2024-03-05T07:08:09Z\",\"Name\":\"n\",\"Type\":\"UserTag\",\"Items\":[{\"RevisionId\":\"r\"}]}", TagDto.class);
r("WrappedResultDto", "{\"Result\":\"success\"}", WrappedResultDto.class);
r("WrappedResultDto.exact", "{\"Result\":\"Success\"}", WrappedResultDto.class);
r("AuthDto", "{\"AccessToken\":\"a\",\"RefreshToken\":\"r\",\"TrackingId\":\"t\",\"UserKey\":\"u\"}", AuthDto.class);
// BinaryByteUnit
var fr = new java.text.DecimalFormat("#,##0.#", java.text.DecimalFormatSymbols.getInstance(Locale.FRANCE));
var us = new java.text.DecimalFormat("#,##0.#", java.text.DecimalFormatSymbols.getInstance(Locale.US));
for (long n : new long[]{0L, 1L, 1000L, 1023L, 1024L, 1536L, 1075L, 1126L, 1177L, 1048575L, 1048576L, 5000000000L, 1234567890123L, 1125899906842624L, 1152921504606846976L, 1280L, 1792L, 2304L, 1049600L}) { System.out.println("U\t" + n + "\t" + com.jakewharton.byteunits.BinaryByteUnit.format(n, us) + "\t" + com.jakewharton.byteunits.BinaryByteUnit.format(n, fr)); }
/exit
